default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: iAnki_development

test:
  <<: *default
  database: iAnki_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD'] %>
