default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: iAnki_development

test:
  <<: *default
  database: iAnki_test

production:
  <<: *default
  database: iAnki_production
  username: iAnki
  password: <%= ENV['IANKI_DATABASE_PASSWORD'] %>
