require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("custom/add_card")
require("custom/delete_card")
require("custom/flip_card")
require("custom/import_csv")
require("custom/suggest_word")
import '../stylesheets/application'